apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-user-microservice
  namespace: user-microservice
spec:
  provider: azure
  secretObjects:
  - secretName: keyvault-secrets
    type: Opaque
    data:
    - objectName: DatabaseConnectionString
      key: DatabaseConnectionString
    - objectName: JwtSecret
      key: JwtSecret
    - objectName: ApiKey
      key: ApiKey
    - objectName: ApplicationInsightsConnectionString
      key: ApplicationInsightsConnectionString
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "315f4f34-ba44-4d15-a447-43e07407a21e"
    keyvaultName: "usermicroservicekv"
    tenantId: "484a1300-3601-4507-8428-d0975c6bf4d1"
    objects: |
      array:
        - |
          objectName: DatabaseConnectionString
          objectType: secret
          objectVersion: ""
        - |
          objectName: JwtSecret
          objectType: secret
          objectVersion: ""
        - |
          objectName: ApiKey
          objectType: secret
          objectVersion: ""
        - |
          objectName: ApplicationInsightsConnectionString
          objectType: secret
          objectVersion: ""